/* tslint:disable */
/* eslint-disable */
/**
 * TeddyCloud API
 * OpenAPI specification for TeddyCloud Backend API
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { Errors, OptionsList, StatsList } from "../models";
import {
    ErrorsFromJSON,
    ErrorsToJSON,
    OptionsListFromJSON,
    OptionsListToJSON,
    StatsListFromJSON,
    StatsListToJSON,
} from "../models";

import { TagTonieCard, TagsTonieCardList, TonieCardProps } from "../../components/tonies/TonieCard";
import { TonieboxCardList, TonieboxCardProps } from "../../components/tonieboxes/TonieboxCard";

export interface ApiSetCloudCacheContentPostRequest {
    body: boolean;
}

export interface ApiUploadCertPostRequest {
    filename?: Array<Blob>;
}

/**
 *
 */
export class TeddyCloudApi extends runtime.BaseAPI {
    /**
     * get all tonieboxes
     */
    async apiGetTonieboxesIndexRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<TonieboxCardList>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/getBoxes`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );
        return new runtime.JSONApiResponse<TonieboxCardList>(response);
    }

    /**
     * get all tonieboxes
     */
    async apiGetTonieboxesIndex(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<TonieboxCardProps[]> {
        const response = await this.apiGetTonieboxesIndexRaw(initOverrides);
        return (await response.value()).boxes;
    }

    /**
     * get tonieBoxLastOnline
     */
    async apiGetLastOnlineRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/internal.last_connection`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse<string>(response);
    }

    /**
     * get tonieBoxLastOnline
     */
    async apiGetLastOnline(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<string> {
        const response = await this.apiGetLastOnlineRaw(overlay, initOverrides);
        const timestamp = await response.value();
        const date = timestamp ? new Date(parseInt(timestamp, 10) * 1000) : "";
        return date.toLocaleString();
    }

    /**
     * get tonieBoxStatus
     */
    async apiGetTonieboxStatusRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/internal.online`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse<boolean>(response);
    }

    /**
     * get tonieBoxStatus
     */
    async apiGetTonieboxStatus(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<boolean> {
        const response = await this.apiGetTonieboxStatusRaw(overlay, initOverrides);
        return await response.value();
    }

    /**
     * get tonieBoxVersion
     */
    async apiGetTonieboxVersionRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/internal.toniebox_firmware.boxIC`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse<string>(response);
    }

    /**
     * get tonieBoxVersion
     */
    async apiGetTonieboxVersion(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<string> {
        const response = await this.apiGetTonieboxVersionRaw(overlay, initOverrides);
        return response.value();
    }

    /**
     * get last played tonie ruid of toniebox
     */
    async apiGetTonieboxLastRUIDRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/internal.last_ruid`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.TextApiResponse(response);
    }

    /**
     * get last played tonie ruid of toniebox
     */
    async apiGetTonieboxLastRUID(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<string> {
        const response = await this.apiGetTonieboxLastRUIDRaw(overlay, initOverrides);
        return await response.value();
    }

    /**
     * get last played tonie time
     */
    async apiGetTonieboxLastRUIDTimeRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/internal.last_ruid_time`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.TextApiResponse(response);
    }

    /**
     * get last played tonie time
     */
    async apiGetTonieboxLastRUIDTime(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<string> {
        const response = await this.apiGetTonieboxLastRUIDTimeRaw(overlay, initOverrides);
        const timestamp = await response.value();
        const date = timestamp ? new Date(parseInt(timestamp, 10) * 1000) : "";
        return date.toLocaleString();
    }

    /**
     * get last IP of toniebox
     */
    async apiGetTonieboxLastIpRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/internal.ip`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.TextApiResponse(response);
    }

    /**
     * get last IP of toniebox
     */
    async apiGetTonieboxLastIp(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<string> {
        const response = await this.apiGetTonieboxLastIpRaw(overlay, initOverrides);
        return await response.value();
    }

    /**
     * get toniebox content dir
     */
    async apiGetTonieboxContentDirRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/core.contentdir`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.TextApiResponse(response);
    }

    /**
     * get toniebox content dir
     */
    async apiGetTonieboxContentDir(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<string> {
        const response = await this.apiGetTonieboxContentDirRaw(overlay, initOverrides);
        return await response.value();
    }

    /**
     * get toniebox API Access
     */
    async apiGetTonieboxApiAccessRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/get/toniebox.api_access`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse<boolean>(response);
    }

    /**
     * get toniebox API access
     */
    async apiGetTonieboxApiAccess(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<boolean> {
        const response = await this.apiGetTonieboxApiAccessRaw(overlay, initOverrides);
        return await response.value();
    }

    /**
     * get core.newBoxesAllowed
     */
    async apiGetNewBoxesAllowedRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        const path = `/api/settings/get/core.allowNewBox`;

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse<boolean>(response);
    }

    /**
     * get core.newBoxesAllowed
     */
    async apiGetNewBoxesAllowed(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.apiGetNewBoxesAllowedRaw(initOverrides);
        return await response.value();
    }

    /**
     * get security mit alert
     */
    async apiGetSecurityMITAlertRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        const path = `/api/settings/get/internal.security_mit.incident`;

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse<boolean>(response);
    }

    /**
     * get security mit alert
     */
    async apiGetSecurityMITAlert(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.apiGetSecurityMITAlertRaw(initOverrides);
        return await response.value();
    }

    /**
     * get all tags
     */
    async apiGetTagIndexRaw(
        overlay?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<TagsTonieCardList>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/getTagIndex`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );
        return new runtime.JSONApiResponse<TagsTonieCardList>(response);
    }

    /**
     * get all tags
     */
    async apiGetTagIndex(
        overlay?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<TonieCardProps[]> {
        const response = await this.apiGetTagIndexRaw(overlay, initOverrides);
        const tags = (await response.value()).tags;

        // remove this if the api returns already the sourceInfo itself:
        // start
        const uniqueSourcePaths = Array.from(
            new Set(
                tags
                    .map((tag) => {
                        const { source } = tag;
                        if (source.startsWith("lib://")) {
                            const pathParts = source.split("/");
                            pathParts.pop();
                            return pathParts.join("/").replace("lib:/", "");
                        }
                        return null;
                    })
                    .filter((source) => source !== null)
            )
        );
        const fetchDataForPath = async (path: any) => {
            try {
                const response = await fetch(
                    `${process.env.REACT_APP_TEDDYCLOUD_API_URL}/api/fileIndexV2?path=${path}&special=library`
                );
                const data = await response.json();
                return { path, data };
            } catch (error) {
                console.error(`Error fetching data for path: ${path}`, error);
                return { path, data: null };
            }
        };
        const results = await Promise.all(uniqueSourcePaths.map(fetchDataForPath));
        // Check for matches and append tonieInfo to tags as sourceInfo
        const updatedTags = tags.map((tag) => {
            const result = results.find((result) => {
                if (result.data && result.data.files) {
                    return result.data.files.some(
                        (file: { name: any }) => tag.source === `lib://${result.path}/${file.name}`.replace("///", "//")
                    );
                }
                return false;
            });
            if (result && result.data && result.data.files) {
                const matchedFile = result.data.files.find(
                    (file: { name: any }) => tag.source === `lib://${result.path}/${file.name}`.replace("///", "//")
                );
                if (matchedFile) {
                    return {
                        ...tag,
                        sourceInfo: matchedFile.tonieInfo
                            ? matchedFile.tonieInfo
                            : { picture: "img_unknown.png", series: matchedFile.name },
                    };
                }
            }
            // If no match found, return the tag as is
            return tag;
        });

        // remove this if the api returns already the sourceInfo itself
        // end

        console.log(updatedTags);
        // repace updatedTags with tags if the api returns already the sourceInfo itself
        return updatedTags;
    }

    /**
     * get tag info
     */
    async apiGetTagInfoRaw(
        ruid: string,
        overlay?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<TagTonieCard>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/getTagInfo?ruid=${ruid}`;
        if (overlay !== "") {
            path = path + "&overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );
        return new runtime.JSONApiResponse<TagTonieCard>(response);
    }

    /**
     * get tag info
     */
    async apiGetTagInfo(
        ruid: string,
        overlay?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<TonieCardProps> {
        const response = await this.apiGetTagInfoRaw(ruid, overlay, initOverrides);

        const tag = (await response.value()).tagInfo;

        // remove this if the api returns already the sourceInfo itself:
        // start
        if (tag.source.startsWith("lib://")) {
            const pathParts = tag.source.split("/");
            pathParts.pop();
            const path = pathParts.join("/").replace("lib:/", "");

            try {
                const response = await fetch(
                    `${process.env.REACT_APP_TEDDYCLOUD_API_URL}/api/fileIndexV2?path=${path}&special=library`
                );
                const data = await response.json();
                if (data && data.files) {
                    console.log(data);
                    const matchedFile = data.files.find(
                        (file: { name: any }) => tag.source === `lib://${path}/${file.name}`.replace("///", "//")
                    );
                    if (matchedFile && matchedFile.tonieInfo) {
                        return {
                            ...tag,
                            sourceInfo: matchedFile.tonieInfo,
                        };
                    }
                }
            } catch (error) {
                console.error(`Error fetching data for path: ${path}`, error);
            }
        }
        // remove this if the api returns already the sourceInfo itself:
        // end

        return tag;
    }

    async apiGetTagIndexMergedAllOverlays(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<TonieCardProps[]> {
        const tonieboxData = await this.apiGetTonieboxesIndex();

        // Fetch tag index for each toniebox and merge the results into one array
        const mergedTonieCards: TonieCardProps[][] = await Promise.all([
            ...tonieboxData.map(async (toniebox) => {
                const tonieCards = await this.apiGetTagIndex(toniebox.ID, initOverrides);
                return tonieCards;
            }),
            this.apiGetTagIndex("", initOverrides),
        ]);

        const flattenedTonieCards = mergedTonieCards.flat();

        // Filter out duplicates based on the ruid AND source property (assume some tags have different content in each overlay)
        const uniqueTonieCards = flattenedTonieCards.filter(
            (tag, index, self) => index === self.findIndex((t) => t.ruid === tag.ruid && t.source === tag.source)
        );

        return uniqueTonieCards;
    }

    /**
     * get all options
     */
    async apiGetIndexGetRaw(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<OptionsList>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        let path = `/api/settings/getIndex`;
        if (overlay !== "") {
            path = path + "?overlay=" + overlay;
        }

        const response = await this.request(
            {
                path: path,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => OptionsListFromJSON(jsonValue));
    }

    /**
     * get all options
     */
    async apiGetIndexGet(
        overlay: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<OptionsList> {
        const response = await this.apiGetIndexGetRaw(overlay, initOverrides);
        return await response.value();
    }

    /**
     * Cache cloud content on local server
     */
    async apiSetCloudCacheContentPostRaw(
        requestParameters: ApiSetCloudCacheContentPostRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError(
                "body",
                "Required parameter requestParameters.body was null or undefined when calling apiSetCloudCacheContentPost."
            );
        }
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "text/plain";

        const response = await this.request(
            {
                path: `/api/settings/set/cloud.cacheContent`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters.body as any,
            },
            initOverrides
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cache cloud content on local server
     */
    async apiSetCloudCacheContentPost(
        requestParameters: ApiSetCloudCacheContentPostRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<void> {
        await this.apiSetCloudCacheContentPostRaw(requestParameters, initOverrides);
    }

    /**
     * Load all available stats.
     */
    async apiStatsGetRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<StatsList>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/stats`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => StatsListFromJSON(jsonValue));
    }

    /**
     * Load all available stats.
     */
    async apiStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatsList> {
        const response = await this.apiStatsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * tell server to write to config file
     */
    async apiTriggerWriteConfigGetRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/triggerWriteConfig`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        if (this.isJsonMime(response.headers.get("content-type"))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * tell server to write to config file
     */
    async apiTriggerWriteConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTriggerWriteConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * upload certificates
     */
    async apiUploadCertPostRaw(
        requestParameters: ApiUploadCertPostRequest,
        overlay?: String,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;

        let path = `/api/uploadCert`;
        if (overlay !== "" && overlay !== undefined) {
            path = path + "?overlay=" + overlay;
        }

        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.filename) {
            requestParameters.filename.forEach((element) => {
                formParams.append("filename", element as any);
            });
        }

        const response = await this.request(
            {
                path: path,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: formParams,
            },
            initOverrides
        );

        if (this.isJsonMime(response.headers.get("content-type"))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * upload certificates
     */
    async apiUploadCertPost(
        requestParameters: ApiUploadCertPostRequest = {},
        overlay?: String,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<string> {
        const response = await this.apiUploadCertPostRaw(requestParameters, overlay, initOverrides);
        return await response.value();
    }
}
